services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD no arquivo .env}"
    ports:
      - "5432:5432"
